title: MalariaGEN DataLab
author: MalariaGEN
copyright: "2021"
logo: images/logo.png
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/malariagen/datalab-guide
  path_to_book              : docs
  branch                    : master
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: ""
  colab_url: ""
  jupyterhub_url: "https://datalab-abafar.malariagen.net"
html:
  use_repository_button : true
  use_issues_button: true
  comments:
    utterances:
      repo: "malariagen/datalab-guide"
      issue-term: "pathname"
      label: "comment"
      theme: "github-light"
      
